name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  push_to_registry:

    name: Push Docker image to Docker Hub

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/fd-app-img
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:

    name: Deploy to EC2 on master branch push

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Prod Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          #USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          #TAG: ${{ steps.meta.outputs.tags }}

      - run: chmod 400 /home/runner/.ssh/deploy_key

      #- run: ssh -i "/home/runner/.ssh/deploy_key" ubuntu@ec2-13-126-127-158.ap-south-1.compute.amazonaws.com -t 'sh /home/ubuntu/pixxel/docker-build.sh'

      #- run: cd /home/ubuntu/pixxel

      #- run: sudo su

      #- run: sh docker-build.sh

          #echo "docker logs -f fd-app:${{ steps.meta.outputs.tags }}"       

    
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |

            echo "Remove containers "
            sudo docker rm -f $(sudo docker ps -a -q)
            
            echo "Remove images "
            sudo docker rmi -f $(sudo docker image ls -q)
            
            echo "Remove Volumes "
            sudo docker volume prune -f 

            echo "Pulling the docker image from the private docker hub repository"
            sudo docker pull harshithapuradh/fd-app-img:master

            echo "Using the pulled docker image to run the docker container"
            sudo docker run -d --name fd-app -p 5001:5001 harshithapuradh/fd-app-img:master
            
            
            
            ## FInally done

   
